import { PATH } from "../hooks/usePath"
import {Dashboard,Teachers,Students,Billing,Settings,Exams,Features} from "../pages/Dashboard"
import { TeachersAddForm, TeachersListForm, TeachersMore } from "../pages/Dashboard/ProfilePages"
import {Login,Register} from "../pages/Login"
export const dashboardRouteList =[
    {
        id:1,
        path:PATH.Dashboard,
        element:<Dashboard/>,
        children:[]
    },
    {
        id:2,
        path:PATH.Teachers,
        element:<Teachers/>,
        children:[
            {
                id:8,
                path:PATH.TeachersListForm,
                element:<TeachersListForm/>
            },
            {
                id:9,
                path:PATH.TeachersAddForm,
                element:<TeachersAddForm/>
            },
            {
                id:10,
                path:PATH.TeachersMore,
                element:<TeachersMore/>
            }
        ]
    },
    {
        id:3,
        path:PATH.Students,
        element:<Students/>,
        children:[]
    },
    {
        id:4,
        path:PATH.Billing,
        element:<Billing/>,
        children:[]
    },
    {
        id:5,
        path:PATH.Settings,
        element:<Settings/>,
        children:[]
    },
    {
        id:6,
        path:PATH.Exams,
        element:<Exams/>,
        children:[]
    },
    {
        id:7,
        path:PATH.Features,
        element:<Features/>,
        children:[]
    },
]
export const LoginRoutes = [
    {
        id:1,
        path:PATH.Login,
        element:<Login/>,
        children:[]
    },
    {
        id:2,
        path:PATH.Register,
        element:<Register/>,
        children:[]
    },
]